FROM node:8.9.3-alpine

ARG API_URL
ARG MOCK_API_URL
ARG OAUTH_AZURE_AD_CALLBACK_URL
ARG APPDYNAMIC_API_KEY
ARG APPDYNAMICS_CONTROLLER_HOST_NAME
ARG APPDYNAMICS_CONTROLLER_PORT
ARG APPDYNAMICS_CONTROLLER_SSL_ENABLED
ARG APPDYNAMICS_AGENT_ACCOUNT_NAME
ARG APPDYNAMICS_AGENT_APPLICATION_NAME
ARG APPDYNAMICS_AGENT_TIER_NAME
ARG APPDYNAMICS_REUSE_NODE
ARG APPDYNAMICS_REUSE_NODE_PREFIX

EXPOSE 80 3001

ENV PORT 80
ENV API_URL=$API_URL
ENV MOCK_API_URL=$MOCK_API_URL
ENV OAUTH_AZURE_AD_CALLBACK_URL=$OAUTH_AZURE_AD_CALLBACK_URL
ENV APPDYNAMIC_API_KEY=$APPDYNAMIC_API_KEY
ENV APPDYNAMICS_CONTROLLER_HOST_NAME=$APPDYNAMICS_CONTROLLER_HOST_NAME
ENV APPDYNAMICS_CONTROLLER_PORT=$APPDYNAMICS_CONTROLLER_PORT
ENV APPDYNAMICS_CONTROLLER_SSL_ENABLED=$APPDYNAMICS_CONTROLLER_SSL_ENABLED
ENV APPDYNAMICS_AGENT_ACCOUNT_NAME=$APPDYNAMICS_AGENT_ACCOUNT_NAME
ENV APPDYNAMICS_AGENT_APPLICATION_NAME=$APPDYNAMICS_AGENT_APPLICATION_NAME
ENV APPDYNAMICS_AGENT_TIER_NAME=$APPDYNAMICS_AGENT_TIER_NAME
ENV APPDYNAMICS_REUSE_NODE=$APPDYNAMICS_REUSE_NODE
ENV APPDYNAMICS_REUSE_NODE_PREFIX=$APPDYNAMICS_REUSE_NODE_PREFIX

WORKDIR /app

ADD ./dist /app

RUN yarn install --production --no-progress

CMD [ "yarn", "run", "start"]
